csv:
  base: ./lib/cr-csv/
  path:
    texts: ./assets/csv_client/texts.csv
    arenas: ./assets/csv_logic/arenas.csv
    rarities: ./assets/csv_logic/rarities.csv
    chest_order: ./assets/csv_logic/chest_order.csv
    clan_chest: ./assets/csv_logic/globals.csv

json:
  base: ./dst/
  cards: ./cards.json
  rarities: ./rarities.json
  chest_order: ./chest_order.json
  clan_chest: ./clan_chest.json

cards:
  - type: Troop
    sckey: 260000{0:02d}
    csv: ./assets/csv_logic/spells_characters.csv
  - type: Building
    sckey: 270000{0:02d}
    csv: ./assets/csv_logic/spells_buildings.csv
  - type: Spell
    sckey: 280000{0:02d}
    csv: ./assets/csv_logic/spells_other.csv

quests:
  base: ./lib/cr-csv/assets/csv_logic/quests
  types:
    - type: attack
      csv: attack.csv
    - type: cast
      csv: cast.csv
    - type: collect
      csv: collect.csv
    - type: daily
      csv: daily.csv
    - type: donate
      csv: donate.csv
    - type: play
      csv: play.csv
    - type: pve
      csv: pve.csv
