csv:
  base: ../lib/cr-csv/
  path:
    texts: ./assets/csv_client/texts.csv
    arenas: ./assets/csv_logic/arenas.csv
    rarities: ./assets/csv_logic/rarities.csv

json:
  base: ../dst/
  cards: ./cards.json
  rarities: ./rarities.json

cards:
  - type: Troops
    sckey: 260000{0:02d}
    csv: ./assets/csv_logic/spells_characters.csv
  - type: Buildings
    sckey: 270000{0:02d}
    csv: ./assets/csv_logic/spells_buildings.csv
  - type: Spells
    sckey: 280000{0:02d}
    csv: ./assets/csv_logic/spells_other.csv

quests:
  base: ../lib/cr-csv/assets/csv_logic/quests
  types:
    - type: attack
      csv: attack.csv
    - type: cast
      csv: cast.csv
    - type: collect
      csv: collect.csv
    - type: daily
      csv: daily.csv
    - type: donate
      csv: donate.csv
    - type: play
      csv: play.csv
    - type: pve
      csv: pve.csv
